create database rental;
USE [rental]
GO
/****** Object:  Table [dbo].[ADMIN]    Script Date: 5/30/2022 6:07:14 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[ADMIN](
	[A_ID] [int] IDENTITY(1,1) NOT NULL,
	[FIRST_NAME] [varchar](20) NOT NULL,
	[LAST_NAME] [varchar](20) NOT NULL,
	[EMAIL] [varchar](20) NOT NULL,
	[PASSWORD] [varchar](20) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[A_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[CLIENT]    Script Date: 5/30/2022 6:07:14 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[CLIENT](
	[C_ID] [int] IDENTITY(1,1) NOT NULL,
	[FIRST_NAME] [varchar](20) NOT NULL,
	[LAST_NAME] [varchar](20) NOT NULL,
	[EMAIL] [varchar](20) NOT NULL,
	[PASSWORD] [varchar](20) NOT NULL,
	[BIRTH_DATE] [date] NULL,
	[STREET] [varchar](10) NULL,
	[ZIP_CODE] [int] NULL,
	[CITY] [varchar](20) NULL,
	[STATE] [varchar](10) NULL,
PRIMARY KEY CLUSTERED 
(
	[C_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[GAME]    Script Date: 5/30/2022 6:07:14 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[GAME](
	[G_ID] [int] IDENTITY(1,1) NOT NULL,
	[V_ID] [int] NULL,
	[A_ID] [int] NULL,
	[G_NAME] [varchar](20) NOT NULL,
	[RATING] [int] NULL,
	[CATEGORY] [varchar](20) NULL,
	[DEVELOP_DATE] [date] NULL,
PRIMARY KEY CLUSTERED 
(
	[G_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[RENT]    Script Date: 5/30/2022 6:07:14 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[RENT](
	[C_ID] [int] NOT NULL,
	[G_ID] [int] NOT NULL,
	[START_DAY] [int] NOT NULL,
	[START_MONTH] [int] NOT NULL,
	[START_YEAR] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[C_ID] ASC,
	[G_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[RENTING_OUT]    Script Date: 5/30/2022 6:07:14 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[RENTING_OUT](
	[R_ID] [int] IDENTITY(1,1) NOT NULL,
	[V_ID] [int] NULL,
	[C_ID] [int] NULL,
	[AMOUNT] [int] NULL,
	[END_DAY] [int] NOT NULL,
	[END_MONTH] [int] NOT NULL,
	[END_YEAR] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[R_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[VENDOR]    Script Date: 5/30/2022 6:07:14 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[VENDOR](
	[V_ID] [int] IDENTITY(1,1) NOT NULL,
	[V_FNAME] [varchar](20) NOT NULL,
	[V_LNAME] [varchar](20) NULL,
PRIMARY KEY CLUSTERED 
(
	[V_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
ALTER TABLE [dbo].[GAME]  WITH CHECK ADD FOREIGN KEY([A_ID])
REFERENCES [dbo].[ADMIN] ([A_ID])
GO
ALTER TABLE [dbo].[GAME]  WITH CHECK ADD FOREIGN KEY([V_ID])
REFERENCES [dbo].[VENDOR] ([V_ID])
GO
ALTER TABLE [dbo].[RENT]  WITH CHECK ADD FOREIGN KEY([C_ID])
REFERENCES [dbo].[CLIENT] ([C_ID])
GO
ALTER TABLE [dbo].[RENT]  WITH CHECK ADD FOREIGN KEY([G_ID])
REFERENCES [dbo].[GAME] ([G_ID])
GO
ALTER TABLE [dbo].[RENTING_OUT]  WITH CHECK ADD FOREIGN KEY([C_ID])
REFERENCES [dbo].[CLIENT] ([C_ID])
GO
ALTER TABLE [dbo].[RENTING_OUT]  WITH CHECK ADD FOREIGN KEY([V_ID])
REFERENCES [dbo].[VENDOR] ([V_ID])
GO
INSERT INTO ADMIN(FIRST_NAME,LAST_NAME,EMAIL,PASSWORD)VALUES('Mohamed','Gamal','mohamedg@gmail.com',01100984581);
INSERT INTO VENDOR (V_FNAME,V_LNAME)VALUES('mohamed','gamal');
INSERT INTO VENDOR (V_FNAME,V_LNAME)VALUES('omar','walid');
INSERT INTO VENDOR (V_FNAME,V_LNAME)VALUES('ahmed','adel');
INSERT INTO VENDOR (V_FNAME,V_LNAME)VALUES('orca','orcawy');
INSERT INTO VENDOR (V_FNAME,V_LNAME)VALUES('ali','attia');
INSERT INTO CLIENT (FIRST_NAME,LAST_NAME,EMAIL,PASSWORD,BIRTH_DATE,STREET,ZIP_CODE,CITY,STATE)VALUES('mohamed','Gemy','mm@b.c',1236,'2000-11-11','mo',4,'giza','faisal');
INSERT INTO CLIENT (FIRST_NAME,LAST_NAME,EMAIL,PASSWORD,BIRTH_DATE,STREET,ZIP_CODE,CITY,STATE)VALUES('omar','Walid','om@b.c ',1111,'2000-01-11','mo', 5 ,'giza','harm');
INSERT INTO CLIENT (FIRST_NAME,LAST_NAME,EMAIL,PASSWORD,BIRTH_DATE,STREET,ZIP_CODE,CITY,STATE)VALUES('gemy',' gamal' ,'a@b.c',12445 , '2000-01-11' ,'mo', 45 ,'helwan','helwan');
INSERT INTO CLIENT (FIRST_NAME,LAST_NAME,EMAIL,PASSWORD,BIRTH_DATE,STREET,ZIP_CODE,CITY,STATE)VALUES('ahmed ',   ' adel' ,  ' a@b,c',     1234 ,   '2000-11-11' ,   'middle' ,   1156  , ' helwan ' , ' Cairo');
INSERT INTO CLIENT (FIRST_NAME,LAST_NAME,EMAIL,PASSWORD,BIRTH_DATE,STREET,ZIP_CODE,CITY,STATE)VALUES('Ali'  ,  'attia'  , ' a@b,c ' ,   12344 ,  ' 2000-11-12' , '  middle '  , 1156   , 'helwan'  , ' Cairo');
INSERT INTO CLIENT (FIRST_NAME,LAST_NAME,EMAIL,PASSWORD,BIRTH_DATE,STREET,ZIP_CODE,CITY,STATE)VALUES( 'mohamed ','gamal '  ,'a@b.c ' ,  1234 ,  ' 2002-01-19 '  , 'middle st.'  ,  124563 ,  ' helwan'  ,  'cairo');
INSERT INTO GAME(V_ID,A_ID,G_NAME,RATING,CATEGORY,DEVELOP_DATE)VALUES(1,1,'farcry',9,'shooting','2020-1-19');
INSERT INTO GAME(V_ID,A_ID,G_NAME,RATING,CATEGORY,DEVELOP_DATE)VALUES(2,1,'fifa',9,'soccer','2020-1-11');
INSERT INTO GAME(V_ID,A_ID,G_NAME,RATING,CATEGORY,DEVELOP_DATE)VALUES(3,1,'lol',9,'RGB','2020-1-12');
INSERT INTO RENT(C_ID,G_ID,START_DAY,START_MONTH,START_YEAR)VALUES(1,1,19,5,2021);
INSERT INTO RENT(C_ID,G_ID,START_DAY,START_MONTH,START_YEAR)VALUES(1,2,15,2,2021);
INSERT INTO RENT(C_ID,G_ID,START_DAY,START_MONTH,START_YEAR)VALUES(1 , 3 , 14 ,5,2021);
INSERT INTO RENT(C_ID,G_ID,START_DAY,START_MONTH,START_YEAR)VALUES(2 ,2, 10 , 5,2022); 
INSERT INTO RENT(C_ID,G_ID,START_DAY,START_MONTH,START_YEAR)VALUES(3 , 3 , 12 , 5 , 2022);
INSERT INTO RENTING_OUT(V_ID,C_ID,AMOUNT,END_DAY,END_MONTH,END_YEAR)VALUES(3,2,330,18,7,2022);
INSERT INTO RENTING_OUT(V_ID,C_ID,AMOUNT,END_DAY,END_MONTH,END_YEAR)VALUES(3,3,10,15,6,2022);

--query1
SELECT GAME.G_NAME FROM GAME where G_ID in (SELECT RENT.G_ID FROM RENT GROUP BY G_ID HAVING  COUNT(C_ID) in (SELECT TOP 1 COUNT(C_ID) as countt FROM RENT GROUP BY G_ID ORDER BY countt DESC));

--query2

select G_NAME from GAME where G_NAME not in (select GAME.G_NAME from GAME,RENT where GAME.G_ID = RENT.G_ID and RENT.START_MONTH >= 5 and RENT.START_YEAR = 2022 );

--query3

SELECT Client.FIRST_NAME+' '+Client.LAST_NAME as Name FROM CLIENT where C_ID in (SELECT RENT.C_ID FROM RENT GROUP BY C_ID HAVING  COUNT(C_ID) in (SELECT TOP 1 COUNT(C_ID) as countt FROM RENT GROUP BY C_ID HAVING MAX(START_YEAR) = 2022 and MAX(START_MONTH)>=5 ORDER BY countt DESC));

--query4

SELECT VENDOR.V_FNAME+' '+VENDOR.V_LNAME as Name FROM VENDOR where V_ID in (SELECT RENTING_OUT.V_ID FROM RENTING_OUT GROUP BY V_ID HAVING  COUNT(V_ID) in (SELECT TOP 1 COUNT(V_ID) as countt FROM RENTING_OUT GROUP BY V_ID HAVING MAX(END_YEAR) = 2022 and MAX(END_MONTH)>=5 ORDER BY countt DESC));

--query5
select V_FNAME+' '+V_LNAME as Names from VENDOR where V_ID not in ( select VENDOR.V_ID  from VENDOR inner join GAME  on VENDOR.V_ID=GAME.V_ID inner join RENT on GAME.G_ID=RENT.G_ID where RENT.START_MONTH>=5 and RENT.START_YEAR=2022);


--query6

select V_FNAME+' '+V_LNAME as Names from VENDOR where VENDOR.V_ID not in (select VENDOR.V_ID from VENDOR inner join GAME on VENDOR.V_ID=GAME.V_ID where GAME.DEVELOP_DATE >='2022-1-1');
